/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gregoryjean-baptiste' at '4/20/16 7:38 PM' with Gradle 2.12
 *
 * @author gregoryjean-baptiste, @date 4/20/16 7:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
