/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gregoryjean-baptiste' at '4/21/16 8:13 PM' with Gradle 2.12
 *
 * @author gregoryjean-baptiste, @date 4/21/16 8:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
